document.addEventListener('DOMContentLoaded',()=>{
const $=id=>document.getElementById(id), ids=['s1','s2','s3','s4'];
const labels=['Purpose','Design/methodology/approach','Findings','Originality/value'];
const cw=t=>(String(t||'').trim().match(/\b[\w’-]+\b/g)||[]).length;
function refresh(){ids.forEach((id,i)=>{const e=$(id),c=$('c'+(i+1));if(e&&c){const n=cw(e.value);c.textContent=`${n} / 100 words`;c.classList.toggle('over',n>100)}});const total=ids.reduce((a,id)=>a+($(id)?cw($(id).value):0),0);if($('overallCount'))$('overallCount').textContent=`Total: ${total} / 500 words`;}
ids.forEach((id,i)=>{const e=$(id);if(e){e.addEventListener('input',refresh);const b=e.closest('.section-box');if(b){const s=b.querySelector('strong');if(s)s.textContent=labels[i];}}});refresh();
const split=t=>(String(t||'').replace(/\s+/g,' ').match(/[^.!?]+(?:[.!?]+|$)/g)||[]).map(x=>x.trim()).filter(Boolean);
const TERMS={purpose:['aim','aims','objective','purpose','investigate','investigates','examine','examines','explore','explores','address','addresses','question','gap','context','focuses','seeks','problem','motivation'],design:['method','methods','methodology','design','sample','participants','respondents','survey','experiment','experimental','interview','interviews','dataset','data','collected','analysis','analyzed','analysed','regression','sem','pls','cfa','efa','procedure','measurement','panel','cross-sectional','longitudinal','qualitative','quantitative'],findings:['result','results','finding','findings','found','revealed','showed','shows','indicated','indicates','demonstrated','demonstrates','significant','significantly','supported','association','effect','relationship','positive','negative','higher','lower'],originality:['original','originality','novel','novelty','value','contribution','contributes','implication','implications','extends','advance','advances','first','new','unique','theoretical','managerial','policy','highlights','underscores']};
function score(s,terms){const t=' '+s.toLowerCase().replace(/[^a-z0-9-]+/g,' ')+' ';return terms.reduce((n,w)=>n+(t.includes(' '+w+' ')?1:0),0)}
function secScore(s,k,i,n){let v=score(s,TERMS[k]),p=i/Math.max(1,n-1),l=s.toLowerCase();if(k==='purpose'&&p<.35)v+=1;if(k==='design'&&p>=.2&&p<.62)v+=.5;if(k==='findings'&&p>=.45&&p<.88)v+=.6;if(k==='originality'&&p>.68)v+=.8;if(k==='purpose'&&/\b(this study|this research|we (aim|investigate|examine|explore)|the aim|the objective|the purpose)\b/.test(l))v+=3;if(k==='design'&&/\b(we (used|collected|analyzed|analysed|conducted|surveyed|estimated)|sample of|participants|respondents)\b/.test(l))v+=3;if(k==='findings'&&/\b(results?|findings?) (show|showed|indicate|indicated|reveal|revealed|suggest|suggested)\b/.test(l))v+=3;if(k==='originality'&&/\b(originality|novel|novelty|contributes|contribution|extends|first study|unique value|implications?)\b/.test(l))v+=3;return v}
function detailedSection(sentences,key){const ranked=sentences.map((s,i)=>({s,i,score:secScore(s,key,i,sentences.length)})).sort((a,b)=>b.score-a.score||a.i-b.i);let picked=[];function tryAdd(x){if(picked.some(p=>p.i===x.i))return false;const test=[...picked,x].sort((a,b)=>a.i-b.i).map(p=>p.s).join(' ');if(cw(test)<=100){picked.push(x);return true}return false}
ranked.filter(x=>x.score>0).forEach(x=>{if(cw(picked.map(p=>p.s).join(' '))<72)tryAdd(x)});
if(!picked.length){const fallback=key==='purpose'?ranked.slice().sort((a,b)=>a.i-b.i):key==='originality'?ranked.slice().sort((a,b)=>b.i-a.i):ranked;for(const x of fallback){if(tryAdd(x))break}}
for(const x of ranked){if(cw(picked.map(p=>p.s).join(' '))>=82)break;tryAdd(x)}
return picked.sort((a,b)=>a.i-b.i).map(p=>p.s).join(' ')}
function convert(){const a=$('abstract'),status=$('status');if(!a)return;const text=a.value.trim();if(text.length<80){if(status){status.textContent='Please enter a fuller unstructured abstract before converting it.';status.className='status error'}return}const ss=split(text);ids.forEach((id,i)=>{if($(id))$(id).value=detailedSection(ss,['purpose','design','findings','originality'][i])});refresh();if(typeof setMode==='function')setMode('structured');else if($('structuredBtn'))$('structuredBtn').click();if(status){status.textContent='A more detailed structured abstract has been created from the original text. Each section is kept within 100 words; please review the section assignment before submission.';status.className='status ok'}}
const btn=$('convertBtn');if(btn)btn.onclick=convert;
const sb=$('structuredBtn');if(sb){const old=sb.onclick;sb.onclick=e=>{const empty=ids.every(id=>!$(id)||!$(id).value.trim());if($('abstract')&&$('abstract').value.trim()&&empty){convert();return}if(typeof old==='function')old.call(sb,e);}};
});